### ISSUE TITLE
Getting error 500 when installing chromedriver with curl

### ISSUE THREAD

**Issue by titanve** [CircleCI-Public/browser-tools-orb#112]
### Orb version
1.4.6

### What happened
Getting error 500 when installing chromedriver with curl `curl: (22) The requested URL returned error: 500`
![image](https://github.com/CircleCI-Public/browser-tools-orb/assets/4803351/195fa23a-48d6-47d8-adde-81670983a99e)

### Expected behavior
Install chromedriver normally without issues

**Comment by benoit-scnd** [comment]
Same issue with the version `1.4.5` and Chrome version `116.0.5845.96`.

**Comment by byrond** [comment]
`1.4.7` seems to fix this for Chrome `120.0.6099.129`, but that generates a different error:
`/bin/bash: line 165: [[: 120.0.6099.129: syntax error: invalid arithmetic operator (error token is ".0.6099.129")`

**Comment by byrond** [comment]
See https://github.com/CircleCI-Public/browser-tools-orb/issues/102 for the Bash error, but updating to 1.4.7 should fix this issue.

**Comment by benoit-scnd** [comment]
The bugfix is in feedback currently: https://github.com/CircleCI-Public/browser-tools-orb/pull/110

**Comment by cvanschalkwijk** [comment]
Same issue here, I can `wget` fine in my local machine but even downloading the file through SSH inside of Circle is causing a 500 response accessing the url directly.  Nothing has changed on my end in code, builds that succeeded yesterday are now failing during this step.

Error during `npm ci`:
```
npm ERR! Saving to file: /tmp/120.0.6099.109/chromedriver/chromedriver-linux64.zip
npm ERR! Current existing ChromeDriver binary is unavailable, proceeding with download and extraction.
npm ERR! Downloading from file:  https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/linux64/chromedriver-linux64.zip
npm ERR! Error status code: 500
```

SSH into a running job and try to access the same file via command line:
```
circleci@a24c51daaad6:~/app$ wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/linux64/chromedriver-linux64.zip
--2024-02-22 14:46:38--  https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/linux64/chromedriver-linux64.zip
Resolving edgedl.me.gvt1.com (edgedl.me.gvt1.com)... 34.104.35.123, 2600:1900:4110:86f::
Connecting to edgedl.me.gvt1.com (edgedl.me.gvt1.com)|34.104.35.123|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2024-02-22 14:46:39 ERROR 500: Internal Server Error.
```

**Comment by titanve** [comment]
Try using the new orb version `1.4.8`

**Comment by titanve** [comment]
new orb version `1.4.8` seems to fix the issue
![image](https://github.com/CircleCI-Public/browser-tools-orb/assets/4803351/a8e27647-06af-4bb3-87d5-f5e93f04bb8b)
