### ISSUE TITLE
Failed to install firefox

### ISSUE THREAD

**Issue by ronaveva** [CircleCI-Public/browser-tools-orb#14]
### Orb version 1.0.0 - 1.0.1
    
    Latest stable version of Firefox is 79.0

    A different version of Firefox is installed (Mozilla Firefox 47.0.1); removing it
    
    gpg: Signature made Tue 21 Jul 2020 02:11:18 AM UTC using RSA key ID BB7D572E
    
    gpg: Good signature from "Mozilla Software Releases <release@mozilla.com>"
    
    gpg: WARNING: This key is not certified with a trusted signature!
    
    gpg:          There is no indication that the signature belongs to the owner.
    
    Primary key fingerprint: 14F2 6682 D091 6CDD 81E3  7B6D 61B7 B526 D98F 0353
    
    Subkey fingerprint: 097B 3130 77AE 62A0 2F84  DA4D F1A6 668F BB7D 572E
    
    gpg: Signature made Mon 20 Jul 2020 09:14:40 PM UTC using RSA key ID BB7D572E

    gpg: Good signature from "Mozilla Software Releases <release@mozilla.com>"

    gpg: WARNING: This key is not certified with a trusted signature!

    gpg:          There is no indication that the signature belongs to the owner.

    Primary key fingerprint: 14F2 6682 D091 6CDD 81E3  7B6D 61B7 B526 D98F 0353

    Subkey fingerprint: 097B 3130 77AE 62A0 2F84  DA4D F1A6 668F BB7D 572E

    Can't open SHA512SUMS: No such file or directory.

    sha256sum: 'standard input': no properly formatted SHA256 checksum lines found

    grep: SHA512SUMS: No such file or directory

    sha512sum: 'standard input': no properly formatted SHA512 checksum lines found

    Exited with code exit status 1

    CircleCI received exit code 1`

It started happening today, tried with 1.0.0 and 1.0.1

**Comment by tkurina** [comment]
Seems to be broken by Mozilla themselves: https://bugzilla.mozilla.org/show_bug.cgi?id=1655844
Current SHA256SUMS: https://archive.mozilla.org/pub/firefox/releases/79.0/SHA256SUMS
Previous (78): https://archive.mozilla.org/pub/firefox/releases/78.0/SHA256SUMS

**Comment by calbach** [comment]
For the lazy, parameterizing the command with the prior Firefox version worked for me:

```
      - browser-tools/install-browser-tools:
          firefox-version: "78.0" # https://github.com/CircleCI-Public/browser-tools-orb/issues/14
```
