### ISSUE TITLE
Install chromedriver step fails without clear error

### ISSUE THREAD

**Issue by jchen-veev** [CircleCI-Public/browser-tools-orb#18]
### What happened

I'm running a  'test' job with a step of    - browser-tools/install-browser-tools , 
all the commands in the step succeed except for install chromedriver which fails and stops the test job.
the console doesn't show any errors during the installation,
only ends with:

Installed version of Google Chrome is 87.0.4280.66
ChromeDriver 87.0.4280.20 will be installed

Exited with code exit status 1
CircleCI received exit code 1

and the step fails.

Job example:
https://app.circleci.com/pipelines/bitbucket/adomiteam/veev-qa-automation-backoffice/51/workflows/c2d584f6-fc5e-411a-a66f-4f8ce81c8acb/jobs/69

### Expected behavior

install chromedriver should succeed or provide an actionable error message

**Comment by dsayling** [comment]
@jchen-veev - could you verify with the latest version of the orb? I believe #19 might have been the issue.

**Comment by aawiegel** [comment]
I tried this recently for the update with Chrome 90 and got the same error using browser-tools@1.1.3

```
Installed version of Google Chrome is 90.0.4430.93
ChromeDriver 90.0.4430.24 will be installed
```

**Comment by brivu** [comment]
Hey @aawiegel,  

I just used your config and tested it out on my own repo and Chrome Driver installed successfully.  I noticed in your pipeline that you were able to install it successfully as well.  

I'm closing this issue for now but feel free to ping me if this issue persists. 

Best, 
Brian
