### ISSUE TITLE
Commands use hyphens, but usage example titles show underscores

### ISSUE THREAD

**Issue by matthew-white** [CircleCI-Public/browser-tools-orb#21]
For version 1.1.3, I'm seeing that the commands themselves use hyphens (for example, `install-browsers`), but the titles of the usage examples show underscores (for example, `install_browsers`). `browser-tools` is the first orb I've used, and it works great, but this difference between hyphen and underscore was an initial point of confusion.

**Comment by felicianotech** [comment]
The command names and the example names are completely separate. They just happen to use similar words here. I can submit a PR to change them regardless if it's confusing.

**Comment by felicianotech** [comment]
My PR was closed. Looks like we won't fix this since this is a cosmetic issue.
