### ISSUE TITLE
[Feature Request] Add ability to run against Chrome Beta/Canary

### ISSUE THREAD

**Issue by unlikelyzero** [CircleCI-Public/browser-tools-orb#23]
### Orb version

1.13

### What happened

We'd like to test chromium versions before they hit the regular stable channel in addition to stable chrome. We'd like to have CircleCI pull chrome channels detailed here: https://www.chromium.org/getting-involved/dev-channel

**Comment by felicianotech** [comment]
This might be a larger change to this orb that it sounds, but I like the idea.

**Comment by felicianotech** [comment]
So we're not going to be adding support for Canary at the moment, especially since it's not available on Linux, but beta builds are incoming shortly.

**Comment by felicianotech** [comment]
The `install-chrome` command now has a `channel` parameter that you can set in v1.4.0.
