### ISSUE TITLE
403 fetch failures when trying to install chrome

### ISSUE THREAD

**Issue by adidahiya** [CircleCI-Public/browser-tools-orb#60]
### Orb version

1.4.0

### What happened

I started getting occasional build failures today during the `browser-tools/install-chrome` step of my workflow. There seem to be various 403 forbidden fetch failures:

- https://app.circleci.com/pipelines/github/palantir/blueprint/3452/workflows/f139396a-59f4-4914-88fa-b80c7e82f10c/jobs/64395/parallel-runs/1
- https://app.circleci.com/pipelines/github/palantir/blueprint/3450/workflows/d0fc162a-64d3-4dae-a3ad-0653d7b61ca5/jobs/64373
- https://app.circleci.com/pipelines/github/palantir/blueprint/3449/workflows/4fb2bb44-7044-483d-91a8-205555156c2b/jobs/64367

I tried upgrading from browser-tools v1.3.0 to v1.4.0 and the problem is still there.

### Expected behavior

No errors when trying to install Chrome.

**Comment by rob4629** [comment]
+1

**Comment by WilsonMinFong** [comment]
We noticed this too, but seems to have resolved itself. Seeing builds get past the `browser-tools/install-chrome` step.
