### ISSUE TITLE
chrome downloading very slow

### ISSUE THREAD

**Issue by laureanorp** [CircleCI-Public/browser-tools-orb#66]
### Orb version

browser-tools: circleci/browser-tools@1.4.1

### What happened

Chrome downloading at speeds as slow as 40kbps

<img width="685" alt="image" src="https://user-images.githubusercontent.com/14150766/216984045-71ca6d05-ff72-4fb4-9b78-ffeda13a82c1.png">

<img width="519" alt="image" src="https://user-images.githubusercontent.com/14150766/216984301-42b9aa46-9199-4c57-80ba-008cd041f008.png">

### Expected behavior

Much faster speeds. Example from yesterday: `Fetched 25.2 MB in 3s (9,720 kB/s) `

Is this related to this orb, or is it a problem with google servers?

**Comment by ArturT** [comment]
[This post](https://github.com/CircleCI-Public/browser-tools-orb/issues/50#issuecomment-1419187342) suggests:

>  it seems the current download rate from http://archive.ubuntu.com/ubuntu is capped at <100kB/s

**Comment by laureanorp** [comment]
We are back to normal speeds now, and indeed this was probably caused my https://status.canonical.com/#/incident/KNms6QK9ewuzz-7xUsPsNylV20jEt5kyKsd8A-3ptQEVUe5iAwdm8JF7ErCrLqPnMAwu3z5Y-lH0alDAJSJH6w==

So I'm closing this. Thanks!
