### ISSUE TITLE
Cannot Install ESR Versions of Firefox

### ISSUE THREAD

**Issue by ErnieCampbell** [CircleCI-Public/browser-tools-orb#7]
### Orb version

circleci/browser-tools@0.1.3

### What happened

I tried to install an ESR version (60.0.2esr) of Firefox.  The build failed because the installation failed.

> Something went wrong; the specified version of Firefox could not be installed

### Expected behavior

Firefox should be installed without error.

### The specific problem

Firefox is actually being installed, but the orb is messing up one of the final steps.  At the end, the orb checks if the actual version of Firefox installed matches the desired version.  The orb code that does this will work for most versions of Firefox, but fails for ESR versions.  The reason for this is that the version reported by `firefox --version` in line 669 of the orb source *does not* include "esr".  It comes back simply as **60.0.2**, instead of **60.0.2esr**, and hence the subsequent `grep` does not find a match.

The orb needs to extract the version number (without "esr") from the version.  It actually does something very similar when installing Geckodriver (line 765).

**Comment by iynere** [comment]
thanks, we'll get this fixed asap! @ErnieCampbell

**Comment by iynere** [comment]
@ErnieCampbell can you confirm on what OS you're seeing this behavior ?

the orb is not really designed to support ESR releases, except on Alpine (e.g., "To install an older release, specify a full semantic version number"—`60.0.2esr` is not really a valid semantic version number)

that said, this is probably an easy fix—would just need to add a bit of string manipulation

**Comment by ErnieCampbell** [comment]
> @ErnieCampbell can you confirm on what OS you're seeing this behavior ?
> 
> the orb is not really designed to support ESR releases—e.g., "To install an older release, specify a full semantic version number," and `60.0.2esr` is not really a valid semantic version number—except on Alpine where `stable` or `esr` are the only options
> 
> that said, this is probably an easy fix—would just need to add a bit of string manipulation

The primary Docker container is `circleci/ruby:2.4.1-stretch-node-browsers`.  Is that sufficient?

**Comment by iynere** [comment]
@ErnieCampbell patched in `circleci/browser-tools@0.1.4`
