### ISSUE TITLE
ChromeDriver install fails with 404

### ISSUE THREAD

**Issue by JasonBarnabe** [CircleCI-Public/browser-tools-orb#76]
### Orb version

circleci/browser-tools@1.4.1

### What happened

https://app.circleci.com/pipelines/github/Simplero/Simplero/53387/workflows/3b9937ed-f077-458b-a523-825a6303e4ae/jobs/63110

"Install ChromeDriver" step fails, output is:

```
Installed version of Google Chrome is 115.0.5790.98 
curl: (22) The requested URL returned error: 404 

Exited with code exit status 22

CircleCI received exit code 22
```

### Expected behavior

Not do that.

**Comment by gorner** [comment]
Was just about to post this, looks like there the ChromeDriver releases were relocated per https://sites.google.com/chromium.org/driver/?pli=1:

> Starting with M115 the latest Chrome + ChromeDriver releases per release channel (Stable, Beta, Dev, Canary) are available at[ the Chrome for Testing availability dashboard](https://googlechromelabs.github.io/chrome-for-testing/). For automated version downloading one can use the convenient [JSON endpoints](https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json).

**Comment by gorner** [comment]
And now I see #75 was posted at the same time which appears to be the same issue.

**Comment by JasonBarnabe** [comment]
He was quicker on the draw, so closing in favour of that one.
