### ISSUE TITLE
does chrome really install on arm64?

### ISSUE THREAD

**Issue by josh-m-sharpe** [CircleCI-Public/browser-tools-orb#87]
I've been trying to get chrome installed on cimg/ruby while running locally on M1 macbook.  This orb suggests that chrome will install on arm64 (Because there is code [here](https://github.com/CircleCI-Public/browser-tools-orb/blob/main/src/scripts/install-chrome.sh#L111-L113)), but everything I've tried ends up with some architecture error, or is not actually installable.

Kinda just wondering if anyone has successfully run chrome on arm64

Thanks!

**Comment by ryanbourdais** [comment]
Hi @josh-m-sharpe there was a change in orb version 1.4.2 that removed chrome installations for arm64 as there is no support from google except for mac machines. That code was left in the chromedriver install in the case that this may change in the future.
