### ISSUE TITLE
Firefox fails to download due to SSL issue

### ISSUE THREAD

**Issue by jocmp** [CircleCI-Public/browser-tools-orb#88]
### Orb version

`circleci/browser-tools@1.4.3` with the Docker `cimg/node:20.4.0` executor

### What happened

The "Install Firefox" step ([source code](https://github.com/CircleCI-Public/browser-tools-orb/blob/main/src/commands/install-firefox.yml)) fails with the following error 

```
System detected as Linux
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   683  100   683    0     0   8877      0 --:--:-- --:--:-- --:--:--  8986
Latest stable version of Firefox is 116.0
^@^@curl: (60) SSL: no alternative certificate subject name matches target host name 'archive.mozilla.org'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

Exited with code exit status 2
```

### Expected behavior

I'd expect Firefox to install without issue. This was working as of about an hour ago. Any ideas about what's changed?

**Comment by camerenisonfire** [comment]
The actual `archive.mozilla.org` SSL certificate is invalid. I don't believe this is a problem with this Orb.

**Comment by fabiosammy** [comment]
@jocmp I know that is not a fix, but if you put `install-firefox: false`, will it run the install?

https://circleci.com/developer/orbs/orb/circleci/browser-tools?version=1.4.3#commands-install-browser-tools

**Comment by jocmp** [comment]
@fabiosammy Thanks for the link. I just spun up a test project to try this out (the specific chrome value is set to an internal project). It fails but due to missing dependencies for Chrome, even with the "browser" variant image.

https://app.circleci.com/pipelines/github/jocmp/demo-browser-ci/3/workflows/b6d26675-dd65-4f82-bc47-e2f3017923c7/jobs/2


Demo config: https://github.com/jocmp/demo-browser-ci/blob/4b26047145f1fdbed2a0f762f5814aabd83668e7/.circleci/config.yml

**Comment by jocmp** [comment]
Looks like it's working again. I'm still not sure why `install_firefox` doesn't work correctly, but my original configuration is fine for now.

- https://github.com/jocmp/demo-browser-ci/blob/7bfd0ed7a59cdb3310074a47ec1c5af48d101976/.circleci/config.yml
- https://app.circleci.com/pipelines/github/jocmp/demo-browser-ci/4/workflows/9bf87fc3-4e75-4a7d-b288-60938db587cc/jobs/3
