### ISSUE TITLE
Can't intall latest geckodriver release on Alpine Linux

### ISSUE THREAD

**Issue by iynere** [CircleCI-Public/browser-tools-orb#9]
### Orb version

latest

### What happened

https://circleci.com/gh/CircleCI-Public/browser-tools-orb/1808

some kind of permissions/execution issue, seemingly

### Expected behavior

geckodriver should be callable/runnable after installation

**Comment by KyleTryon** [comment]
Firefox is broken on Alpine as well, no reported issues of it and no interaction on this issue as well. Going to remove alpine from the next major update. We can add it back if requested. I believe a lot of the logic for alpine will need to be updated.
