### ISSUE TITLE
ChromeDriver install fail

### ISSUE THREAD

**Issue by HagiCohn** [CircleCI-Public/browser-tools-orb#91]
**Orb version**
browser-tools: circleci/browser-tools@1.4.4

**What happened**
"Install ChromeDriver" step fails, output is:

Installed version of Google Chrome is 116.0.5845.140 
ChromeDriver 116.0.5845.140 will be installed
116.0.5845.140 will be installed
curl: (22) The requested URL returned error: 404 

Exited with code exit status 22

**Comment by timdiggins** [comment]
FYI This is a duplicate of #90 (which has more detail).

**Comment by ryanbourdais** [comment]
For everyone tracking this issue, orb version v1.4.5 has now been published and now features a fallback to prevent this issue from occuring
