### ISSUE TITLE
Chrome Version field is not working on macOS builds

### ISSUE THREAD

**Issue by e-grapp** [CircleCI-Public/browser-tools-orb#93]
### Orb version

`1.4.4`

### What happened

When declaring no version, a release that is not available gets downloaded (`116.0.5845.140`)
![image](https://github.com/CircleCI-Public/browser-tools-orb/assets/104026596/cd3bd0b9-6999-436a-91ef-ded5ddfff738)

When declaring a version, it still downloads the aforementioned version 

Snippet from Config:
```
- browser-tools/install-chrome:
    chrome-version: 116.0.5845.96
    replace-existing: true
- browser-tools/install-chromedriver
```

Response: 

```
System detected as MacOS
Installed version of Google Chrome is 116.0.5845.140 
ChromeDriver 116.0.5845.140 will be installed
116.0.5845.140 will be installed
curl: (22) The requested URL returned error: 404

Exited with code exit status 22
```

- https://app.circleci.com/pipelines/github/e-grapp/sandbox/239/workflows/9972139d-d99f-47db-8540-3a9f8b5a50e1/jobs/269

This occurs on a variety of Xcode images and on both M1/Intel Execution environments.

- Using a different xcode image results in same behavior - https://app.circleci.com/pipelines/github/e-grapp/sandbox/240/workflows/15e59d82-04f5-4ded-a293-cab012a4a145/jobs/270 
- Switching over to M1 - https://app.circleci.com/pipelines/github/e-grapp/sandbox/242/workflows/62a105e2-3c51-49bf-a71b-e126b07f34c5/jobs/272

### Expected behavior

The version defined in the `chrome-version` parameter is the one that is installed at runtime when using the orb command rather than the latest stable release.

**Comment by alanjclark** [comment]
It looks like this is more related to messaging in the orb. The version of ChromeDriver in question has not yet been published by Google:

https://chromedriver.chromium.org/downloads

**Comment by ryanbourdais** [comment]
For everyone tracking this issue, orb version v1.4.5 has now been published and now features a fallback to prevent this issue from occuring
