### ISSUE TITLE
ChromeDriver install fail 

### ISSUE THREAD

**Issue by karlentwistle** [CircleCI-Public/browser-tools-orb#95]
### Orb version
browser-tools: circleci/browser-tools@1.4.5

### What happened
"Install ChromeDriver" step fails, output is:

```
Chrome version major is 116
Installed version of Google Chrome is 116.0.5845.187 
404
Matching Chrome Driver Version 404'd, falling back to first matching major version.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   567  100   567    0     0   6968      0 --:--:-- --:--:-- --:--:--  7000
New ChromeDriver version to be installed: 116
116 will be installed
curl: (22) The requested URL returned error: 404

Exited with code exit status 22
```

### Expected behavior

It should install whatever the latest version of Chrome can be downloaded.

---

I think the issue is with this LOC https://github.com/CircleCI-Public/browser-tools-orb/blob/5cd25d04778b08a8ae9341350f4233aa58bc2670/src/scripts/install-chromedriver.sh#L160 
its returning `116` instead of ` 116.0.5845.96`

For example:

```
curl https://googlechromelabs.github.io/chrome-for-testing/latest-versions-per-milestone.json | grep -o "116.*"  | grep -o "version.*" | grep -o '\:*'"116"'.*,' | sed 's/".*//'
```

**Comment by chefvivica** [comment]
Same issue here with 1.4.5

**Comment by chefvivica** [comment]
> Same, and previous workaround doesn't work for me either
> 
> ```
> - browser-tools/install-browser-tools:
>     chrome-version: 116.0.5845.96 # TODO: remove when chromedriver downloads are fixed
> ```
> 
> ```
> Google Chrome is not currently installed; installing it
> Preparing Chrome installation for Debian-based systems
> 2023-09-12 19:17:35 URL:https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_116.0.5845.96-1_amd64.deb [96765132/96765132] -> "/tmp/chrome.deb" [1]
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Note, selecting 'google-chrome-stable' instead of '/tmp/chrome.deb'
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
> google-chrome-stable : Depends: libu2f-udev but it is not installable
> E: Unable to correct problems, you have held broken packages.
> /bin/bash: line 129: google-chrome-stable: command not found
> Google Chrome v116.0.5845.96 (stable) failed to install.
> 
> Exited with code exit status 1
> ```
> 
> (on the 'Install Google Chrome' step)

Did you use 1.4.4 for this workaround?

**Comment by karlentwistle** [comment]
For a workaround we're using

```
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.4
```

```
- browser-tools/install-chrome:
          chrome-version: 116.0.5845.96 # TODO: remove -> https://github.com/CircleCI-Public/browser-tools-orb/issues/95
```

**Comment by ryanbourdais** [comment]
I'm looking into it right now, this was actually caused by an a change in the api endpoint, the `timestamp` contains `116` so the logic using attempts to grab the version number from there instead of the milestone. This should be a decently easy/quick fix.  Output from [this endpoint](https://googlechromelabs.github.io/chrome-for-testing/latest-versions-per-milestone.json): ```{"timestamp":"2023-09-12T18:09:06.116Z","milestones":{"113":{"milestone":"113","version":"113.0.5672.63","revision":"1121455"},"114":{"milestone":"114","version":"114.0.5735.133","revision":"1135570"},"115":{"milestone":"115","version":"115.0.5790.170","revision":"1148114"},"116":{"milestone":"116","version":"116.0.5845.96","revision":"1160321"},"117":{"milestone":"117","version":"117.0.5938.62","revision":"1181205"},"118":{"milestone":"118","version":"118.0.5993.3","revision":"1192594"},"119":{"milestone":"119","version":"119.0.6004.0","revision":"1194959"}}}```

**Comment by ryanbourdais** [comment]
Pull Request opened, comments and reviews are much appreciated. I am hoping that this is the end of this chrome driver saga, but I'll keep an eye on this repository in the coming days to make sure.

**Comment by ryanbourdais** [comment]
A new version of this orb has been cut, v1.4.6, and should resolve this issue. I will leave this issue open for the remainder of the week in case this issue is not resolved

**Comment by secobarbital** [comment]
1.4.6 worked for a few days when it was installing chrome v116, now it is failing again after installing v117. Setting the chrome-version causes the same problem as before:

```
Google Chrome is not currently installed; installing it
Preparing Chrome installation for Debian-based systems
2023-09-16 21:02:14 URL:https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_116.0.5845.187-1_amd64.deb [96665460/96665460] -> "/tmp/chrome.deb" [1]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'google-chrome-stable' instead of '/tmp/chrome.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 google-chrome-stable : Depends: libu2f-udev but it is not installable
                        Depends: libvulkan1 but it is not installable
E: Unable to correct problems, you have held broken packages.
/bin/bash: line 130: google-chrome-stable: command not found
Google Chrome v116.0.5845.187 (stable) failed to install.

Exited with code exit status 1
```

**Comment by ryanbourdais** [comment]
@secobarbital that seems to be a separate issue, can you open a new issue with a build link?
