### ISSUE TITLE
Chrome 119: Chrome failed to start

### ISSUE THREAD

**Issue by FGoessler** [CircleCI-Public/browser-tools-orb#99]
### Orb version

`1.4.5` as well as `1.4.6` (latest)

### What happened

Our CI pipelines started to fail to execute specs due to the upgrade from Chrome 118 to Chrome 119.

The error we are getting for all of our tests that rely on Chromedriver is:

```
Selenium::WebDriver::Error::SessionNotCreatedError:
              session not created: Chrome failed to start: exited normally.
                (session not created: DevToolsActivePort file doesn't exist)
                (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

This seems to be some sort of running or installation issue with Google Chrome/Chromedriver.

Previously working version of Chrome: `118.0.5993.117`
Now used version of Chrome: `119.0.6045.105`

Our config in the jobs steps:
```
      - browser-tools/install-browser-tools:
          install-firefox: false
```

Note: We also tried to downgrade the Chroem version via the `chrome-version` option but that fails on installation and is probably another issue. 

### Expected behavior

The specs should run as expected.

**Comment by FGoessler** [comment]
Removed some additional log extraction steps from Chrome in after_each hooks and am now getting a slightly different error:
```
Selenium::WebDriver::Error::WebDriverError:
            unable to connect to /home/circleci/.webdrivers/chromedriver 127.0.0.1:9515
```

But still the issue seems to be that Chrome/Chroemdriver isn't starting up correctly or staying alive and I have no idea why...

**Comment by snyaggarwal** [comment]
Until yesterday things were good for us, but today Chrome driver is not starting. We are on 1.4.6 with chrome/driver 120.0.6099.109.
We tried with SSH and it looks good manually. But without ssh it fails.
Any update on this?

**Comment by marboledacci** [comment]
There is a new release for the orb, I hope it helps with this issue.
